### ISSUE TITLE
Ardan Labs | Modules (Parts 1, 2 & 3)

### ISSUE THREAD

**Issue by atc0005** [enocom/gopher-reading-list#118]
- https://www.ardanlabs.com/blog/2019/10/modules-01-why-and-what.html
- https://www.ardanlabs.com/blog/2019/12/modules-02-projects-dependencies-gopls.html
- https://www.ardanlabs.com/blog/2019/12/modules-03-minimal-version-selection.html

I didn't spot a common landing/index page for the series.

**Comment by enocom** [comment]
Thanks for this -- it's probably time to feature modules more prominently. I'll work these in.
