### ISSUE TITLE
Add link to Chinese version

### ISSUE THREAD

**Issue by enocom** [enocom/gopher-reading-list#161]
There's a similar list of Chinese blog posts here: https://github.com/qichengzx/gopher-reading-list-zh_CN.

Let's add a link to the README.

/cc @qichengzx

**Comment by qichengzx** [comment]
> There's a similar list of Chinese blog posts here: https://github.com/qichengzx/gopher-reading-list-zh_CN.
> 
> Let's add a link to the README.
> 
> /cc @qichengzx

Thanks a lot, this is a great encouragement to me.
