### ISSUE TITLE
Tensorflow + Go blog post?

### ISSUE THREAD

**Issue by galeone** [enocom/gopher-reading-list#18]
Hi, I made a blog post about Tensorflow + Go: https://pgaleone.eu/tensorflow/go/2017/05/29/understanding-tensorflow-using-go/

Since there's no a specific category for such kind of posts, I just want to discuss with you if this could be a good entry for your list and in which category should be placed. I'd be happy to open a PR for adding the link in case of your approval (and suggestion/creation of the adequate category)!

**Comment by enocom** [comment]
@galeone I recall reading your article when it came out last year and it's a great article. The article's focus is Tensorflow and less Go, though, so I think it's not a great fit for this list. Nonetheless, thanks for the suggestion. 😄

**Comment by galeone** [comment]
No problem, thank you for this project!
