### ISSUE TITLE
404 url

### ISSUE THREAD

**Issue by qichengzx** [enocom/gopher-reading-list#181]
[Go memory ballast: How I learned to stop worrying and love the heap](https://blog.twitch.tv/go-memory-ballast-how-i-learnt-to-stop-worrying-and-love-the-heap-26c2462549a2) has been deleted.

**Comment by enocom** [comment]
I’m surprised the link checking isn’t picking these 404s up. Anyways thanks for this. I’ll fix the CI build to catch these.

**Comment by qichengzx** [comment]
it's redirect to https://blog.twitch.tv/zh-tw/ , I'm not sure it is ok in other country or not.
