### ISSUE TITLE
Learn Go by writing tests

### ISSUE THREAD

**Issue by enocom** [enocom/gopher-reading-list#20]
[Learn Go by Writing tests](https://dev.to/quii/learn-go-by-writing-tests--m63)

**Comment by donkov** [comment]
Hello

**Comment by enocom** [comment]
@donkov Did you want to comment on the addition of this blog post to the list?

**Comment by ilyaglow** [comment]
Table driven tests are not mentioned, but the idea is great though

**Comment by enocom** [comment]
Also, [this](https://github.com/quii/learn-go-with-tests) is related.

**Comment by NeroCube** [comment]
Does load testing meet this issue?[Vegeta](https://github.com/tsenart/vegeta) is a load testing tool and library.Maybe you can introduce it.
