### ISSUE TITLE
Dead URL (404)

### ISSUE THREAD

**Issue by crims1n** [enocom/gopher-reading-list#200]
"[Creating My First Web Application with Go](https://rosalita.github.io/building-a-web-app-with-go/)" under `Beginner > Web` appears to be broken now.
![go404](https://user-images.githubusercontent.com/50759465/176773877-f68ceae0-a517-40ca-8a48-0bd7ca6837cd.png)

**Comment by enocom** [comment]
Thanks for digging up the right URL!
