### ISSUE TITLE
Go Links

### ISSUE THREAD

**Issue by enocom** [enocom/gopher-reading-list#23]
[Here's](https://github.com/nleiva/go-links) another list of helpful Go resources.

/cc @nleiva

**Comment by nleiva** [comment]
I'm running a diff. This is a first sets of links I enjoyed that might be worth adding here.

### Some basics

- [How to Write Go Code](https://golang.org/doc/code.html)
- [How to avoid Go gotchas](http://divan.github.io/posts/avoid_gotchas/)

### Code Design

- [Go Patterns](https://github.com/tmrts/go-patterns)
- [Go best practices, six years in](http://peter.bourgon.org/go-best-practices-2016/)
- [Structuring Applications in Go](https://medium.com/@benbjohnson/structuring-applications-in-go-3b04be4ff091)
- [Aspects of a good Go library](https://medium.com/@cep21/aspects-of-a-good-go-library-7082beabb403)

### Miscellaneous

- [GoDS (Go Data Structures)](https://github.com/emirpasic/gods)
- [Gophers, please tag your releases](https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases)

**Comment by nleiva** [comment]
There are also some categories that could be ported.

### Community

- [Go Forum](https://forum.golangbridge.org/)
- [Gophers Slack](https://gophers.slack.com/)
- [Reddit](https://www.reddit.com/r/golang/)
- [golang-nuts](https://groups.google.com/forum/#!forum/golang-nuts)

### Blogs/Channels

- [Go Walkthrough](https://medium.com/go-walkthrough)
- [Dave Cheney](https://dave.cheney.net/)
- [Gopher Academy](https://blog.gopheracademy.com/)
- [Skills Matter](https://skillsmatter.com/explore?q=tag%3Ago)
- [Failing Forward](https://www.youtube.com/channel/UCqRfhD3bKs-6gc5lPh2fRVw)
- [JustForFunc](https://www.youtube.com/channel/UC_BzFbxG2za3bp5NRRRXJSw)
- [Gopher Academy](https://www.youtube.com/channel/UCx9QVEApa5BKLw9r8cnOFEA)
- [The Go Programming Language](https://www.youtube.com/user/gocoding)
- [GopherData](http://gopherdata.io/)
- [Learn To Code](https://www.youtube.com/user/toddmcleod)
- [Go Ahead](https://jbrandhorst.com/)
- [Sourcegraph](https://about.sourcegraph.com/go/)
- [Golangbot](https://golangbot.com/)
- [GopherVids](http://gophervids.appspot.com/)
- [Learn Go Programming](https://blog.learngoprogramming.com/)
- [Applied Go](https://appliedgo.net/)
- [golangspec](https://medium.com/golangspec)


Not actually reading links, but cool anyways:

### Gophers

- [Gophers under CC0 license](https://github.com/egonelbre/gophers)
- [Gopher Artwork](https://github.com/ashleymcnamara/gophers)

### Run Examples

- [The Go Play Space](https://goplay.space/)
- [The Go Playground](https://play.golang.org/)

### Priceless

- [Gopherize Me](https://gopherize.me)

**Comment by enocom** [comment]
Thank you for the suggestions!

Since this is a curated and fixed-length reading list, I'm interested in the most useful and relevant blog posts about the language, as opposed to collections of code or community resources. All the material above is worth knowing about, though, and so if you can spare the time, I would recommend checking that [Awesome Go](https://github.com/avelino/awesome-go) has the suggestions above.

From all the suggestions above, four links stand out. Here's a summary:

## Added
- [How to Write Go Code](https://golang.org/doc/code.html)
- [Structuring Applications in Go](https://medium.com/@benbjohnson/structuring-applications-in-go-3b04be4ff091)

## Already in the list
- [How to avoid Go gotchas](http://divan.github.io/posts/avoid_gotchas/)
- [Go best practices, six years in](http://peter.bourgon.org/go-best-practices-2016/)

I've made these changes in cf69e5b9a73a7ee78038fdbafac39b9447ebaa54.
