### ISSUE TITLE
Remove all paywalled Medium posts

### ISSUE THREAD

**Issue by enocom** [enocom/gopher-reading-list#254]
Medium posts are often behind a paywall. For those that are we should remove them from this list. This list should only be freely available material.

**Comment by inancgumus** [comment]
We need to carefully consider the impact of this decision. There are dedicated Medium authors who invest a lot in their content, and it wouldn't be fair to overlook their efforts. Additionally, the links in this repository help people access useful posts, and some individuals would be willing to pay to read that content.

**Comment by enocom** [comment]
This would only be for the posts that are now behind a paywall like the first one. I wouldn’t want to remove any of these paywalls posts, but this is supposed to be a list of free resources. For example when I added the first post about why a person should learn Go, it was free to read. Now it’s not.

**Comment by enocom** [comment]
Updated the title to make it clear the articles that are still free to read aren’t going anywhere.

**Comment by enocom** [comment]
Paywalled:

- https://medium.com/a-journey-with-go/go-asynchronous-preemption-b5194227371c
- https://medium.com/@kevalpatel2106/why-should-you-learn-go-f607681fad65
- https://medium.com/a-journey-with-go/go-introduction-to-the-escape-analysis-f7610174e890

Moved:
- https://teivah.medium.com/when-to-use-generics-in-go-36d49c1aeda to https://100go.co/9-generics/
