### ISSUE TITLE
The Go Programming Language exercises

### ISSUE THREAD

**Issue by yangbinnnn** [enocom/gopher-reading-list#26]
Here: https://github.com/torbiak/gopl

**Comment by enocom** [comment]
Nice find! I'm understand having answers to the exercises from *The Go Programming Language* are super helpful, but I'm not certain that they are a good fit to this reading list. I see it as more of a nice to have than a must have.

That said, I'm open to thinking to second-order lists as part of this project, e.g., here's a list of exercises and their answers, or some such. Are there similar resources you know about?

**Comment by yangbinnnn** [comment]
Approval!

I'd help for the secord-order lists, `exercise` as important as `reading`.

**Comment by enocom** [comment]
[Here](https://github.com/go-training/go-transaction-example) are some more useful exercises worth adding to a second list.

**Comment by enocom** [comment]
And [this](https://gophercises.com/).

**Comment by enocom** [comment]
After almost two months, I'm thinking a list of exercises probably isn't the right fit for this reading list. Feel free to keep appending possible additions and if we get enough of a critical mass, we can re-open this.
