### ISSUE TITLE
Included examples to guide how to make transaction on Mongodb using Golang.

### ISSUE THREAD

**Issue by appleboy** [enocom/gopher-reading-list#27]
See the repo: https://github.com/go-training/go-transaction-example

Thanks.

**Comment by enocom** [comment]
Thanks for the suggestion! This looks very interesting. I wonder if this belongs on a list like the one discussed in #26.

**Comment by appleboy** [comment]
LGTM

**Comment by enocom** [comment]
Using #26 to track all exercise-related content. I've added a link over there for https://github.com/go-training/go-transaction-example.
