### ISSUE TITLE
Suggestion: How to Use go:generate

### ISSUE THREAD

**Issue by carlmjohnson** [enocom/gopher-reading-list#33]
https://blog.carlmjohnson.net/post/2016-11-27-how-to-use-go-generate/

**Comment by enocom** [comment]
This looks really good. Thanks!

Now the hard part. What post should it replace?

**Comment by carlmjohnson** [comment]
😱

**Comment by enocom** [comment]
There is [this](https://blog.gopheracademy.com/advent-2015/reducing-boilerplate-with-go-generate/) which is definitely good, although I find your post easier to read quickly.

Would you be open to adding that post as further reading to your own?

**Comment by carlmjohnson** [comment]
Sure, I can add a link to mine.

**Comment by enocom** [comment]
Let me know when you've added the link and I'll make the change.

Otherwise, I'm happy to accept pull requests if you'd like the contribution credit.

**Comment by carlmjohnson** [comment]
I updated the page. The article now ends with a further reading link out to Gopher Academy.

**Comment by enocom** [comment]
Thanks!
