### ISSUE TITLE
Add separate list for online books

### ISSUE THREAD

**Issue by enocom** [enocom/gopher-reading-list#4]
Among them would be things like:

- [Essential Go](https://www.programming-books.io/essential/go/)
- [Go Bootcamp](http://www.golangbootcamp.com/)
- [Building Web Apps with Go](https://www.gitbook.com/book/codegangsta/building-web-apps-with-go/details)

**Comment by enocom** [comment]
Another book:

- [Build a Web Application with Golang](https://github.com/astaxie/build-web-application-with-golang)

**Comment by dgryski** [comment]
Also https://github.com/dariubs/GoBooks

**Comment by enocom** [comment]
Thanks! I suppose `go-perfbook` might belong on this book list too.

**Comment by dgryski** [comment]
Perfbook is already in the performance section. I don't know if it needs to be listed twice.

**Comment by enocom** [comment]
Another addition:

- [Go Internals](https://github.com/teh-cmc/go-internals)

**Comment by enocom** [comment]
It's tempting to make such a list, but [https://github.com/dariubs/GoBooks](https://github.com/dariubs/GoBooks) is pretty close to what I would want to make.

Closing to avoid duplicate effort.
