### ISSUE TITLE
A list to check

### ISSUE THREAD

**Issue by Hertz** [enocom/gopher-reading-list#6]
Unfortunately I don't have time to sort them, but I guess some of these should really be included in the list.

https://gophercises.com/
https://blog.cloudflare.com/using-go-as-a-scripting-language-in-linux/
https://news.ycombinator.com/item?id=15856111
https://news.ycombinator.com/item?id=15191920
https://www.youtube.com/watch?v=fZh8uCInEfw&feature=youtu.be&t=13m36s
https://www.youtube.com/watch?v=K1EJBmwg9EQ
https://www.youtube.com/watch?v=D5tDubyXLrQ
https://www.youtube.com/watch?v=ak97oH0D6fI
https://www.youtube.com/watch?v=WVZ7yMvxImo
https://www.youtube.com/watch?v=32f6JrQPV8c
https://www.gitbook.com/book/astaxie/go-system-programming/details
https://astaxie.gitbooks.io/build-web-application-with-golang/content/en/index.html
https://peter.bourgon.org/go-best-practices-2016/
http://openmymind.net/Introduction-To-Go-Structures-Data-Instances/
https://npf.io/2017/03/3.5yrs-500k-lines-of-go/
https://medium.com/@tjholowaychuk/profiling-golang-851db2d9ae24#.lccwsc23p
https://blog.golang.org/profiling-go-programs
https://news.ycombinator.com/item?id=15895173
https://go-book.appspot.com/interfaces.html
https://rockfloat.com/post/learning-golang-templates.html
http://www.boyter.org/2017/03/golang-solution-faster-equivalent-java-solution/
https://www.barrucadu.co.uk/posts/etc/2016-08-25-three-months-of-go.html
https://www.jonathan-petitcolas.com/2015/01/27/playing-with-websockets-in-go.html
http://www.minaandrawos.com/2014/09/25/class-factory-in-golang-google-go/
https://github.com/byrnedo/mapcast
http://spf13.com/presentation/MongoDB-and-Go/
https://golang.org/doc/articles/go_command.html
http://stackoverflow.com/questions/6395076/in-golang-using-reflect-how-do-you-set-the-value-of-a-struct-field
https://blog.golang.org/laws-of-reflection
http://studygolang.com/articles/2439
https://blog.golang.org/concurrency-is-not-parallelism
https://talks.golang.org/2012/splash.article
https://beego.me/
https://blog.golang.org/defer-panic-and-recover
http://blog.josephmisiti.com/parsing-json-responses-in-golang
https://github.com/mindreframer/golang-stuff
https://github.com/kildevaeld/go-acl/blob/master/acl.go
https://gobyexample.com/atomic-counters
http://marcio.io/2015/07/handling-1-million-requests-per-minute-with-golang/
http://www.j15r.com/blog/2015/01/25/Game_Development_in_Go
https://www.dotnetperls.com/time-go
https://godoc.org/github.com/sourcegraph/webloop
https://www.reddit.com/r/golang/comments/3wfnru/switching_from_php_to_go/
https://jackcanty.com/build-a-web-crawler-in-go.html
https://elithrar.github.io/article/vue-react-ember-server-golang/
https://blog.acolyer.org/2017/02/02/fencing-off-go-liveness-and-safety-for-channel-based-programming/
https://jannewmarch.gitbooks.io/network-programming-with-go-golang-/content/
https://github.com/asciimoo/wuzz
https://github.com/golang/proposal/blob/master/design/12914-monotonic.md
https://talks.golang.org/2014/readability.slide#1
https://docs.iris-go.com/custom-http-errors.html
https://gobyexample.com/closures
http://blog.charmes.net/2015/07/reverse-proxy-in-go.html
http://tleyden.github.io/
https://github.com/cayleygraph/cayley
http://divan.github.io/posts/go_concurrency_visualize/
https://rakyll.org/latency-profiling/
https://github.com/kataras/golog
https://medium.com/@matryer/introducing-vice-go-channels-across-many-machines-bcac1147d7e2
https://blog.cloudflare.com/sidh-go/
https://segment.com/blog/allocation-efficiency-in-high-performance-go-services/
https://sohlich.github.io/post/go_makefile/
https://commandcenter.blogspot.ro/2017/09/go-ten-years-and-climbing.html
https://github.com/alecthomas/chroma
http://www.golang-book.com/
https://dave.cheney.net/2015/07/02/why-go-and-rust-are-not-competitors
http://www.integralist.co.uk/posts/profiling-go/
http://davidwong.fr/goasm/
http://agniva.me/go/2017/08/27/fun-with-go-assembly.html
https://joeshaw.org/understanding-go-panic-output/
https://codeburst.io/understanding-solid-principles-interface-segregation-principle-b2d57026cf6c
https://blog.codeship.com/improving-ruby-performance-with-rust/
https://github.com/maxpert/raspchat/releases/tag/v1.0.0-alpha
https://blog.learngoprogramming.com/5-gotchas-of-defer-in-go-golang-part-ii-cc550f6ad9aa
https://ewanvalentine.io/microservices-in-golang-part-5/
https://segment.com/blog/5-advanced-testing-techniques-in-go/
https://deadbeef.me/2018/01/go-gotchas
https://github.com/rivo/tview
https://www.rapidloop.com/blog/golang-channels-tips-tricks.html?h
https://github.com/sysdream/hershell
https://news.ycombinator.com/item?id=16162094
https://blog.wallaroolabs.com/2018/01/go-go-go-stream-processing-for-go/
https://secdevops.ai/hacking-with-go-packet-crafting-and-manipulation-in-golang-pt-1-f31cdb066e3a
https://ieftimov.com/golang-datastructures-linked-lists
https://9vx.org/post/a-malloc-idiom-in-go/
https://blog.merovius.de/2018/02/25/persistent_datastructures_with_go.html
https://scene-si.org/2018/02/28/interfaces-in-go/

**Comment by enocom** [comment]
Thanks! I'll take a look.

**Comment by enocom** [comment]
After reading all these posts, three in particular stand out as especially useful:

- [BUFFERED CHANNELS IN GO: TIPS & TRICKS](https://www.rapidloop.com/blog/golang-channels-tips-tricks.html)
- [Build a Web Crawler in Go](https://jackcanty.com/build-a-web-crawler-in-go.html)
- [Handling 1 Million Requests per Minute with Go](http://marcio.io/2015/07/handling-1-million-requests-per-minute-with-golang/)

I'm going to see any of these posts fit into the list.

**Comment by enocom** [comment]
Done! Thanks for the suggestions.
