### ISSUE TITLE
Repo name is confusing

### ISSUE THREAD

**Issue by jackbraj** [enocom/gopher-reading-list#9]
I mistook it for the old [gopher protocol](https://en.wikipedia.org/wiki/Gopher_(protocol)).  It sounded like an archive of gopher.

**Comment by enocom** [comment]
Yes, there is some confusion around the term "gopher." People who program in the Go programming language are typically called "gophers," hence the name of this repo. It seems to me the language is better known than the protocol these days, but I could be wrong.

Did you know there is [another programming language](https://en.wikipedia.org/wiki/Go!_(programming_language)) called "Go!"?

**Comment by jackbraj** [comment]
Yes, I know about Go programming language, but I didn't know that Go programmers are called "gophers".   And you are right that gopher is an old and outdated thing which I too believe that people nowadays have far less exposure to than Go programming language.

So Its good idea to bury the Gopher protocol even deeper.
