### ISSUE TITLE
Switch to Circle CI

### ISSUE THREAD

**Issue by enocom** [enocom/gopher-reading-list#95]
/cc @mvxt

**Comment by enocom** [comment]
Want to just send a PR? You have to be a collaborator to be assigned.

**Comment by mvxt** [comment]
Does this work? I could fork and PR if that's what you prefer.

**Comment by mvxt** [comment]
Will get to this later tonight, have something else I'm working on right now

**Comment by appleboy** [comment]
Another solution: drone http://cloud.drone.io

**Comment by enocom** [comment]
I've been curious to try CircleCI for awhile now. I'll keep drone in mind though if Circle doesn't work out.

**Comment by enocom** [comment]
Fixed in ca5cf826edad0036384b02f57afe072cc27f361a

**Comment by Kyslik** [comment]
@enocom why the change?

**Comment by enocom** [comment]
Just wanted to try it out. No other good reason, really.
